
type Query {
  carMakes: [CarMakeView]
  carMakeByName(name: String!): CarMakeView
  carMake(id: Int!): CarMakeView
}

type Mutation {
  createCarMake(carMakeInput: CarMakeInput): CarMakeView
  createOrGetCarMake(carMakeInput: CarMakeInput): CarMakeView
  updateCarMake(carMakeInput: CarMakeInput): CarMakeView
  deleteCarMake(id: Int!): CarMakeRemoveResponse
}

type CarMakeRemoveResponse  {
    deletedCarMakeId: Int
}

type CarMakeView  {
    id: Int!
    name: String!
}

input CarMakeInput  {
    id: Int
    name: String!
}
