
type Query {
  carModels: [CarModelView]
  carModelByName(name: String!, carMakeId: Int!): CarModelView
  carModel(id: Int!): CarModelView
}

type Mutation {
  createCarModel(carModelInput: CarModelInput): CarModelView
  createOrGetCarModel(carModelInput: CarModelInput): CarModelView
  updateCarModel(carModelInput: CarModelInput): CarModelView
  deleteCarModel(id: Int!): CarModelRemoveResponse
}

type CarModelRemoveResponse  {
    deletedCarModelId: Int
}

type CarModelView  {
    id: Int!
    name: String!
    carMake: CarMakeView!
}

input CarModelInput  {
    id: Int
    name: String!
    carMakeId: Int!
}
