export enum SortMode {
    NATURAL = "Default",
    ID_ASC = "ID - Ascending",
    ID_DESC = "ID - Descending",
    FIRST_NAME_ASC = "First Name - Ascending",
    FIRST_NAME_DESC = "First Name - Descending",
    LAST_NAME_ASC = "Last Name - Ascending",
    LAST_NAME_DESC = "Last Name - Descending",
    EMAIL_ASC = "Email - Ascending",
    EMAIL_DESC = "Email - Descending",
    VIN_ASC = "VIN - Ascending",
    VIN_DESC = "VIN - Descending",
    MANUFACTURED_DATE_ASC = "Manufactured Date - Ascending",
    MANUFACTURED_DATE_DESC = "Manufactured Date - Descending",
    AGE_OF_VEHICLE_ASC = "Age of Vehicle - Ascending",
    AGE_OF_VEHICLE_DESC = "Age of Vehicle - Descending",
    CREATED_AT_ASC = "Created At - Ascending",
    CREATED_AT_DESC = "Created At - Descending",
}