version: '3.0'
services:

  postgres:
    image: postgres:9.6.21-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgraphile:
    image: postgraphile-service
    depends_on:
      - postgres
    build:
      context: ./postgraphile
    environment:
      DATABASE_URL: postgres://postgres:example@postgres:5432/postgres
      PORT: 5000

  redis:
    image: redis:6.2.1-alpine3.13

  bullboard:
    image: deadly0/bull-board:1.7.2
    ports:
      - 3002:3000
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  minio:
    image: minio/minio:RELEASE.2021-03-26T00-00-41Z-35-g5cce9361b
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio:/data
    command: server /data

  socketcluster:
    image: socketcluster/socketcluster:v16.0.1
    ports:
      - 8000:8000

  bulk-process-service:
    image: bulk-process-service
    depends_on:
      - postgraphile
      - minio
      - backend-service
    build:
      context: ./bulk-process-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BACKEND_HOST: backend-service
      BACKEND_PORT: 3000
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: minio
      MINIO_SECRETKEY: minio123
      MINIO_BUCKET: test

  backend-service:
    image: backend-service
    ports:
      - 3000:3000
    depends_on:
      - postgraphile
      - minio
    build:
      context: ./backend
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SOCKETCLUSTER_HOST: socketcluster
      SOCKETCLUSTER_PORT: 8000
      POSTGRAPHILE_HOST: postgraphile
      POSTGRAPHILE_PORT: 5000
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESSKEY: minio
      MINIO_SECRETKEY: minio123
      MINIO_BUCKET: test

  frontend-service:
    image: frontend-service
    ports:
      - 4200:4200
    depends_on:
      - backend-service
    build:
      context: ./frontend
    environment:
      BACKEND_HOST: localhost
      BACKEND_PORT: 3000
      SOCKETCLUSTER_HOST: localhost
      SOCKETCLUSTER_PORT: 8000

volumes:
  postgres:
    driver: local
  minio:
    driver: local