version: '3.0'
services:

  postgres:
    image: postgres:9.6.21-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2.1-alpine3.13
    ports:
      - 6379:6379

  minio:
    image: minio/minio:RELEASE.2021-03-26T00-00-41Z-35-g5cce9361b
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio:/data
    command: server /data

  postgraphile:
    image: postgraphile-service
    ports:
      - 5000:5000
    depends_on:
      - postgres
    build:
      context: ./postgraphile
    environment:
      DATABASE_URL: postgres://postgres:example@postgres:5432/postgres
      PORT: 5000

volumes:
  postgres:
    driver: local
  minio:
    driver: local